### ISSUE TITLE
Proxy Host

### ISSUE THREAD

**Issue by deff-dev** [Sander0542/terraform-provider-nginxproxymanager#51]
Hi, now your provider can add proxy host with certificate?

**Comment by Sander0542** [comment]
Creating proxy hosts are supported, but creating a certificate using this provider is not possible yet. I am adding support for creating certificates in issue https://github.com/Sander0542/terraform-provider-nginxproxymanager/issues/5.

https://registry.terraform.io/providers/Sander0542/nginxproxymanager/latest/docs/resources/proxy_host

**Comment by deff-dev** [comment]
Thx for answer, i'll waiting new version
